#ifndef CPUFEATURES_H
#define CPUFEATURES_H

#define NUM_OF_ADDSUB_STATIONS 3
#define NUM_OF_LOAD_STATIONS 5
#define NUM_OF_STORE_STATIONS 5
#define NUM_OF_MULDIV_STATIONS 2

#define NUM_OF_REGISTERS 6

#define MEMORY_SIZE 512

#define QUEUE_SIZE 6

#define ADD_CLK_LATENCY 2
#define SUB_CLK_LATENCY 2
#define LOAD_CLK_LATENCY 2
#define STORE_CLK_LATENCY 2
#define MUL_CLK_LATENCY 10
#define DIV_CLK_LATENCY 40

#define ADDSUB_STATIONS_NAME "Add"
#define MULDIV_STATIONS_NAME "Mul"
#define LOAD_STATIONS_NAME "Load"
#define STORE_STATIONS_NAME "Store"

#endif // CPUFEATURES_H
